export const mockAthlete = {
  id: 12345,
  resource_state: 1,
  username: 'bon.bikes',
  firstname: 'bob',
  lastname: 'biker',
  city: '',
  state: '',
  country: '',
  sex: '',
  premium: true,
  created_at: '',
  updated_at: '',
  badge_type_id: 100,
  profile_medium: '',
  profile: '',
  friend: '',
  follower: '',
  follower_count: 100,
  friend_count: 50,
  mutual_friend_count: 10,
  athlete_type: 1,
  date_preference: '',
  measurement_preference: 'metric',
  clubs: [],
  ftp: 300,
  weight: 75,
  bikes: [],
  shoes: [],
};

export const mockStravaSession = {
  token_type: 'token',
  expires_at: Math.round(+new Date(2099, 12, 31) / 1000),
  expires_in: 181164654564564,
  refresh_token: 'abcdef',
  access_token: 'kjghkjhiughu',
  athlete: mockAthlete,
};

export const mockAthleteStats = {
  biggest_ride_distance: 300,
  biggest_climb_elevation_gain: 1280,
  recent_ride_totals: {
    count: 1688,
    distance: 76824,
    moving_time: 1536,
    elapsed_time: 57,
    elevation_gain: 12300,
    achievement_count: 17,
  },
  recent_run_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  recent_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  ytd_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  ytd_run_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  ytd_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_ride_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_run_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
  all_swim_totals: {
    count: 0,
    distance: 0,
    moving_time: 0,
    elapsed_time: 0,
    elevation_gain: 0,
    achievement_count: 0,
  },
};
