export const TestIds = {
  headerAppBarTestId: 'COMPONENTS_HEADER_HEADER_APP_BAR',
  homeViewComponent: 'VIEWS_HOME_COMPONENT',
  productTable: 'COMPONENTS_PRODUCTS_PRODUCT_TABLE_PRODUCT_TABLE',
  productDeleteModal: 'COMPONENTS_PRODUCTS_PRODUCT_TABLE_PRODUCT_DELETE_MODAL',
};
