export {
  isAuthLoadingAction,
  isActivitiesLoadingAction,
  isAthleteLoadingAction,
  isStatsLoadingActions,
  authenticateWithStravaAction,
  authenticateWithStravaDoneAction,
  fetchStravaActivitiesAction,
  fetchStravaActivitiesDoneAction,
  fetchStravaAthleteAction,
  fetchStravaAthleteDoneAction,
  fetchStravaAthleteStatsAction,
  fetchStravaAthleteStatsDoneAction,
  isActivityLoadingAction,
  fetchStravaActivityAction,
  fetchStravaActivityDoneAction,
  clearStravaActivityAction,
  isActivityStreamLoadingAction,
  fetchActivityStreamAction,
  fetchActivityStreamDoneAction,
  clearActivityStreamAction,
} from 'src/reducers/strava.reducer';
